# Use the official MariaDB image from Docker Hub
FROM mariadb:11.5-rc

# Environment variables
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=springstories
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin1234

# Expose port 3306 to allow external connections
EXPOSE 3306
